version: '3'

services:
  node_backend:
    container_name: node_usersapp
    image: node_usersapp:0.0.1
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=node_db  
      - DB_USER=user
      - DB_PASSWORD=password123
      - DB_NAME=usersapp_db
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=usersapp_db
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: 
